feat: weather flares new design
virus-rpi/satellytes.com pull request #11
Opened 2023-07-12 12:40 UTC by virus-rpi

**Changes:**
1. ***Snowflakes:***
    - Number of Snowflakes reduced to 100 from 200
    - Snowflakes move slower
    - Snowflakes move left and right while falling
    - Snowflakes now have different sizes
2. ***Clouds:***
    - Clouds now move randomly

2023-07-12 13:02 UTC, milljoniaer approved these changes
Nice one! Please have a look at my two naming related comment.

https://juniortoexpert.com/de/namenskonvention-fur-variablen/ for reference

2023-07-12 13:02 UTC, milljoniaer commented on src/components/content/heroes/aurora/precipitationEffect.tsx
> +interface precipitationData {
Please use PascalCase here

2023-07-12 13:02 UTC, milljoniaer commented on src/components/content/heroes/aurora/precipitationEffect.tsx
> +    transform: translateX(${Math.random() * 200 - 100}px);
nice, cool effect 👍

2023-07-12 13:02 UTC, milljoniaer commented on src/components/content/heroes/aurora/precipitationEffect.tsx
>    }
I am quite late in recognizing it, but please use kebap-case for file names in this project: `precipitation-effect.tsx`

2023-07-12 13:55 UTC, milljoniaer reviewed
I just found an issue please have a look at the comment

2023-07-12 13:55 UTC, milljoniaer commented on src/components/content/heroes/aurora/precipitationEffect.tsx
> +    transform: translateX(${Math.random() * 400 - 200}px);
Hmm, Math.random() only runs once here for all snowflakes, that is not what we intended. Please have a look how to randomize this for each snowflake.

Maybe this helps: https://medium.com/nerd-for-tech/may-14-random-css-animations-using-styled-components-in-react-dda83d9afb62

2023-07-13 12:22 UTC, hofmann-felix requested changes
Richtig stark, dass du schon so weit bist und das Design so gut umgesetzt hast 🙌 Hätte nicht gedacht, dass das Projekt so schnell voran geht. Weiter so :) 

Ein paar Änderungsvorschläge hätte ich trotzdem noch (s. Kommentare). Das Review zu den Änderungen in `precipitation-effect.tsx`, `weather-api.test.ts` und `weather-api.ts` kommt noch, habe ich zeitlich leider nicht mehr geschafft

2023-07-13 12:22 UTC, hofmann-felix commented on src/components/content/heroes/aurora/aurora-animation.ts
> + * as I didn't want to spend time processing it, although it's fun, but it's distracting fun.
Nice, danke dir fürs Ausbessern 🙏

2023-07-13 12:22 UTC, hofmann-felix commented on src/components/content/heroes/aurora/aurora-components.tsx
> +      case WeatherType.NotSet:
Die Cases kannst du entfernen

2023-07-13 12:22 UTC, hofmann-felix commented on src/components/content/heroes/aurora/aurora-components.tsx
> +  weather?: WeatherType;
Ich glaube weather muss nicht optional sein 
```suggestion
  weather: WeatherType;
```

2023-07-13 12:22 UTC, hofmann-felix commented on src/components/content/heroes/aurora/aurora-components.tsx
> +  left: -30%;
Die negativen Prozentwerte zur Positionierung sind wahrscheinlich nicht gerade die beste Lösung, weil:
1. sie schwer nachzuvollziehen sind (vor allem für jemanden, der den Code das erste mal ließt)
2. sie zu einem komischen Verhalten führen, wenn die Fenstergöße neu angepasst wird 

Ich würde versuchen hier eine Lösung mit positiven `px` bzw. `vw + vh` Werten zu finden. Du kannst ja mal in flare.ts zur Inspiration schauen

2023-07-13 12:22 UTC, hofmann-felix commented on src/components/content/heroes/aurora/aurora-components.tsx
> +export const AuroraRainyFlareColor4 = styled.div`
Nummerierte Komponenten sind in der Regel ein Anzeichen dafür, dass man das ganze besser strukturieren kann. Eventuell macht es Sinn nur eine `Flare` Komponente zu haben und die jeweiligen Eigenschaften als Prop zu setzen (ähnlich wie in `flare.ts`)

2023-07-13 12:22 UTC, hofmann-felix commented on src/components/content/heroes/aurora/aurora-components.tsx
> +            <CloudOverlay6 />
Hier haben wir wieder das Problem mit den nummerierten Komponenten. Wahrscheinlich ist es hier auch sinnvoll ein prop einzubauen, dass die verschiedenen Ausprägungen der Komponente beeinflusst.

2023-07-13 12:22 UTC, hofmann-felix commented on src/components/content/heroes/aurora/aurora-components.tsx
Sehr gutes Naming und auch eine sehr gute Idee einen extra File dafür zu erstellen 🙌

2023-07-13 12:22 UTC, hofmann-felix commented on src/components/content/heroes/aurora/aurora-types.ts
Wir brauchen diese Enums an vielen Stellen. Deswegen ist es absolut sinnvoll hier einen einen neuen File zu erstellen. Gut gelöst von dir 👍

2023-07-13 12:22 UTC, hofmann-felix commented on src/components/content/heroes/aurora/aurora.tsx
>    function getSource(type?: AuroraType) {
Wenn du im Projekt global nach `function` suchst wirst du so gut wie keine Treffer finden, weil wir fast nur Arrow Functions nutzen. Deine Lösung ist auf gar keinen Fall falsch, aber ich würde die Funktion trotzdem zu einer Arrow Function ändern, damit es einheitlich ist (`const getSource = (type?: AuroraType) => {...}`)

2023-07-13 12:22 UTC, hofmann-felix commented on src/components/content/heroes/aurora/aurora.tsx
> +        toggleWeather().then();
Das `.then()` hast du vermutlich wegen dem warning eingebaut. Mein Vorschlag wäre es `.then()` zu entfernen und toggleWeather nicht `async` zu machen, z.B. so:

```
  const toggleWeather = () => {
    if (weather === WeatherType.NotSet) {
      getWeather().then((weather) => {setWeather(weather);}).catch(() => {setWeather(WeatherType.NotSet);})
    } else {
      setWeather(WeatherType.NotSet);
    }
  };
```

2023-07-13 12:22 UTC, hofmann-felix commented on src/components/content/heroes/aurora/aurora.tsx
> +    }
Die Logik würde ich eher direkt in `AuroraBackground` schreiben. Also das `background-image` in `AuroraBackground` mit einer Bedingung setzten.

2023-07-13 12:22 UTC, hofmann-felix commented on src/components/content/heroes/aurora/flare.ts
> -  --flare-rotate: 0deg;
Nice, danke fürs Mitdenken 💪

2023-07-14 12:22 UTC, hofmann-felix approved these changes

2023-07-14 12:45 UTC, merged